style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/ik-serverless/repository-to-change.git
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject