name: dummy
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  dummy:
    name: dummy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Greeting
      run: |
        echo "Hello. This is dummy workflow..."